export const adminPage = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Quefa 商户运营中心</title>
  <style>
    :root{--bg:#f4f7fb;--panel:#fff;--ink:#172033;--muted:#718096;--line:#e6ebf2;--brand:#3157d5;--brand2:#6d5dfc;--good:#158467;--warn:#c47a16;--bad:#c14444;--shadow:0 16px 40px rgba(31,49,86,.08)}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.55 Inter,"PingFang SC","Microsoft YaHei",sans-serif}.hidden{display:none!important}button,input,select,textarea{font:inherit}
    .app{display:grid;grid-template-columns:236px 1fr;min-height:100vh}.side{background:#17244a;color:#d9e2ff;padding:26px 18px;position:fixed;inset:0 auto 0 0;width:236px}.brand{display:flex;gap:12px;align-items:center;padding:0 10px 28px}.logo{width:38px;height:38px;border-radius:12px;background:linear-gradient(145deg,#6e7cff,#26c5d9);display:grid;place-items:center;color:white;font-weight:800}.brand b{display:block;color:#fff;font-size:17px}.brand small{color:#8fa5d6}.nav{display:grid;gap:7px}.nav button{border:0;background:transparent;color:#aebee4;text-align:left;padding:12px 14px;border-radius:10px;cursor:pointer}.nav button:hover,.nav button.on{color:white;background:rgba(255,255,255,.1)}.nav i{font-style:normal;display:inline-block;width:25px}.side-foot{position:absolute;bottom:24px;left:28px;color:#7288b8;font-size:12px}
    main{grid-column:2;padding:26px 32px 50px;min-width:0}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}.top h1{font-size:25px;margin:0}.top p{margin:3px 0 0;color:var(--muted)}.badges{display:flex;gap:8px;flex-wrap:wrap}.badge{padding:7px 11px;border-radius:99px;background:#e9edf4;color:#526078;font-size:12px}.badge.good{background:#e4f7f0;color:var(--good)}.badge.warn{background:#fff3dd;color:var(--warn)}
    .view{display:none}.view.on{display:block}.grid{display:grid;gap:18px}.cards{grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:18px}.card,.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow)}.card{padding:20px}.card span{color:var(--muted);font-size:13px}.card strong{display:block;font-size:26px;margin-top:7px;letter-spacing:-.5px}.card small{color:#9aa6b6}.panel{padding:22px;margin-bottom:18px}.panel-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:18px}.panel h2{font-size:17px;margin:0}.panel h3{font-size:15px;margin:0 0 14px}.hint{color:var(--muted);font-size:13px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.field{display:grid;gap:7px}.field label{font-weight:600}.field input,.field select{width:100%;border:1px solid #dfe5ee;border-radius:10px;background:#fff;padding:11px 12px;outline:none}.field input:focus,.field select:focus{border-color:#7d8eea;box-shadow:0 0 0 3px rgba(49,87,213,.09)}.field small{color:var(--muted)}.span2{grid-column:1/-1}.secret{display:flex;gap:8px}.secret input{flex:1}.statusline{display:flex;align-items:center;gap:8px;margin:4px 0 16px;padding:11px 13px;background:#f7f9fc;border-radius:10px}.dot{width:8px;height:8px;border-radius:50%;background:#b6bfcc}.dot.good{background:#22a87c}.btn{border:0;border-radius:10px;padding:10px 15px;cursor:pointer;background:#edf1f7;color:#34425c;font-weight:600}.btn.primary{background:linear-gradient(135deg,var(--brand),var(--brand2));color:white}.btn.danger{background:#fff0f0;color:var(--bad)}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}
    .products{grid-template-columns:repeat(3,minmax(0,1fr))}.product{padding:20px}.product-title{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:17px}.product-title b{font-size:16px}.product-title small{display:block;color:var(--muted)}.switch{position:relative;width:42px;height:24px}.switch input{opacity:0;width:0}.switch span{position:absolute;inset:0;background:#ccd4df;border-radius:20px;cursor:pointer}.switch span:before{content:"";position:absolute;width:18px;height:18px;left:3px;top:3px;border-radius:50%;background:white;transition:.2s}.switch input:checked+span{background:#28a47b}.switch input:checked+span:before{transform:translateX(18px)}
    .toolbar{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.toolbar .field{min-width:160px}.toolbar .btn{height:42px}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:12px}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:12px 13px;border-bottom:1px solid #edf0f5;text-align:left;font-size:12px}th{color:#64728b;background:#f8fafc;position:sticky;top:0}td strong{font-size:13px}.money.plus{color:var(--good)}.money.minus{color:var(--bad)}.tag{padding:4px 7px;border-radius:6px;background:#eef1f6;color:#59677f}.tag.good{background:#e4f7f0;color:var(--good)}.tag.bad{background:#ffeded;color:var(--bad)}.empty{text-align:center;padding:44px;color:var(--muted)}
    .callout{padding:14px 16px;border-radius:12px;background:#fff7e8;color:#8a5a12;margin-bottom:18px;border:1px solid #f4dfb5}.callout.good{background:#eaf8f2;color:var(--good);border-color:#ccebdd}.test-flow{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.test-step{padding:12px;border-radius:10px;background:#f7f9fc;color:var(--muted)}.test-step.on{background:#e9edff;color:var(--brand);font-weight:700}.test-step.done{background:#e4f7f0;color:var(--good)}.test-result{padding:16px;border:1px solid var(--line);border-radius:12px;background:#fbfcfe}.test-result strong{font-size:17px}.test-result .row{display:flex;justify-content:space-between;gap:12px;padding:5px 0}.session-input{width:100%;border:1px solid #dfe5ee;border-radius:10px;padding:12px;resize:vertical;font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}.session-input:focus{outline:none;border-color:#7d8eea;box-shadow:0 0 0 3px rgba(49,87,213,.09)}
    .login{position:fixed;inset:0;background:radial-gradient(circle at 30% 20%,#304e99,#101a36 60%);display:grid;place-items:center;z-index:20}.login-box{width:min(420px,calc(100% - 32px));background:#fff;border-radius:22px;padding:34px;box-shadow:0 28px 80px rgba(0,0,0,.3)}.login-box h1{margin:0 0 5px}.login-box p{color:var(--muted);margin:0 0 24px}.login-box .field{margin-bottom:15px}.error{color:var(--bad);min-height:22px}.toast{position:fixed;right:24px;bottom:24px;background:#172033;color:#fff;padding:12px 18px;border-radius:10px;box-shadow:var(--shadow);z-index:30}.modal{position:fixed;inset:0;background:rgba(17,27,50,.5);z-index:25;display:grid;place-items:center}.modal-box{background:#fff;border-radius:16px;padding:24px;width:min(480px,calc(100% - 30px))}.modal h3{margin-top:0}
    @media(max-width:1050px){.cards{grid-template-columns:repeat(2,1fr)}.products{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.span2{grid-column:auto}.test-flow{grid-template-columns:1fr}}
    @media(max-width:720px){.app{display:block}.side{position:static;width:auto;padding:14px}.brand{padding:0 4px 12px}.nav{display:flex;overflow:auto}.nav button{white-space:nowrap}.side-foot{display:none}main{padding:20px 14px}.top{align-items:flex-start;flex-direction:column}.cards{grid-template-columns:1fr 1fr}.card strong{font-size:20px}}
  </style>
</head>
<body>
<div id="login" class="login">
  <form id="loginForm" class="login-box">
    <div class="logo">Q</div><h1>商户运营中心</h1><p>配置支付与上游、管理商品价格、查看订单财务。</p>
    <div class="field"><label>管理员账号</label><input value="admin" disabled></div>
    <div class="field"><label>管理员密码</label><input id="password" type="password" autocomplete="current-password" required placeholder="请输入后台密码"></div>
    <div id="loginError" class="error"></div><button class="btn primary" style="width:100%">安全登录</button>
  </form>
</div>
<div class="app">
  <aside class="side"><div class="brand"><div class="logo">Q</div><div><b>Quefa 商户中心</b><small>运营控制台</small></div></div>
    <nav class="nav">
      <button class="on" data-view="overview"><i>▦</i>经营概览</button>
      <button data-view="config"><i>⚙</i>接口配置</button>
      <button data-view="products"><i>◇</i>商品与供货价</button>
      <button data-view="test"><i>▶</i>联调测试</button>
      <button data-view="orders"><i>≡</i>订单与财务</button>
    </nav><div class="side-foot">密钥加密保存 · 全站 HTTPS</div>
  </aside>
  <main>
    <header class="top"><div><h1 id="title">经营概览</h1><p id="subtitle">查看交易、结算与利润数据</p></div><div class="badges"><span id="payBadge" class="badge">支付：读取中</span><span id="zovoBadge" class="badge">上游：读取中</span><button id="logout" class="btn">退出</button></div></header>
    <section id="overview" class="view on">
      <div class="grid cards"><div class="card"><span>成功履约订单</span><strong id="mOrders">0</strong><small>平台结算口径</small></div><div class="card"><span>支付宝实际收款</span><strong id="mReceipt">¥0.00</strong><small>已支付且未退款</small></div><div class="card"><span>平台应得差价</span><strong id="mPlatform">¥0.00</strong><small>实收 − 供货价</small></div><div class="card"><span>我方毛利</span><strong id="mProfit">¥0.00</strong><small>供货价 − 上游成本</small></div></div>
      <div class="panel"><div class="panel-head"><div><h2>经营口径</h2><div class="hint">只有“支付成功 + 履约成功 + 未退款”的订单进入平台结算与毛利。</div></div><button class="btn" onclick="go('orders')">查看明细</button></div><div id="recent"></div></div>
    </section>
    <section id="config" class="view">
      <form id="configForm">
        <div class="panel"><div class="panel-head"><div><h2>支付宝电脑网站支付</h2><div class="hint">用户直接付款到您的支付宝商户，异步回调地址已自动生成。</div></div></div><div id="alipayStatus" class="statusline"><span class="dot"></span><span>读取中</span></div>
          <div class="form-grid"><div class="field"><label>运行模式</label><select name="payment_mode"><option value="mock">测试模式（不真实收款）</option><option value="alipay">正式支付宝</option></select></div><div class="field"><label>支付宝 App ID</label><input name="alipay_app_id" placeholder="留空表示不修改"></div><div class="field"><label>支付宝商户 PID / Seller ID</label><input name="alipay_seller_id" placeholder="留空表示不修改"></div><div class="field"><label>应用私钥</label><textarea name="alipay_private_key" rows="5" style="width:100%;border:1px solid #dfe5ee;border-radius:10px;padding:11px" placeholder="粘贴应用私钥；留空表示不修改"></textarea></div><div class="field"><label>支付宝公钥</label><textarea name="alipay_public_key" rows="5" style="width:100%;border:1px solid #dfe5ee;border-radius:10px;padding:11px" placeholder="粘贴支付宝公钥；留空表示不修改"></textarea></div><div class="field span2"><label>支付宝异步通知地址</label><input id="notifyUrl" readonly><small>复制到支付宝开放平台；系统只相信验签并主动查单后的结果。</small></div></div>
        </div>
        <div class="panel"><div class="panel-head"><div><h2>上游充值接口</h2><div class="hint">App ID 与 API 密钥仅在服务端使用，用户和平台都不会看到上游或 CDK。</div></div></div><div id="zovoStatus" class="statusline"><span class="dot"></span><span>读取中</span></div><div class="form-grid"><div class="field"><label>运行模式</label><select name="zovo_mode"><option value="mock">测试模式</option><option value="live">正式上游</option></select></div><div class="field"><label>App ID（ak_ 开头）</label><input name="zovo_app_id" placeholder="例如 ak_xxx；留空表示不修改"></div><div class="field span2"><label>API 密钥 / App Secret（sk_ 开头）</label><input name="zovo_api_key" type="password" placeholder="留空表示不修改"><small>这是实际鉴权密钥，请勿填写截图中的 ak_ App ID。</small></div></div></div>
        <div class="actions"><button type="submit" class="btn primary">保存并立即生效</button></div>
      </form>
    </section>
    <section id="products" class="view"><div class="panel"><div class="panel-head"><div><h2>商品与供货价</h2><div class="hint">平台供货价是双方结算基准；平台可以自行决定用户最终售价，我们不设售价上限。</div></div></div><div id="productGrid" class="grid products"></div></div></section>
    <section id="test" class="view">
      <div class="callout"><b>这是真实链路测试。</b> 创建订单本身不扣款；打开支付宝并完成付款后会真实收款；最后确认提交时会购买充值码并扣除上游余额。测试账号不能已有同类订阅。</div>
      <div class="test-flow"><div id="testStep1" class="test-step on">1. 创建并支付订单</div><div id="testStep2" class="test-step">2. 校验并确认邮箱</div><div id="testStep3" class="test-step">3. 提交充值并查看结果</div></div>
      <div class="panel"><div class="panel-head"><div><h2>载入已有已付款测试单</h2><div class="hint">页面刷新后，可从这里继续之前的测试，不需要重复付款。</div></div><button id="loadExistingTestOrder" type="button" class="btn primary">载入订单</button></div><div class="field"><label>已付款测试单</label><select id="existingTestOrder"><option value="">读取中...</option></select></div></div>
      <div class="panel"><div class="panel-head"><div><h2>创建测试订单</h2><div class="hint">只显示已启用且允许销售的商品，售价不得低于平台供货价。</div></div></div>
        <form id="testOrderForm" class="form-grid"><div class="field"><label>测试商品</label><select id="testProduct" required></select></div><div class="field"><label>测试售价</label><input id="testPrice" type="number" min="0" step="0.01" required></div><div class="actions span2"><button id="createTestOrder" class="btn primary">创建真实支付宝订单</button></div></form>
      </div>
      <div id="testOrderPanel" class="panel hidden"><div class="panel-head"><div><h2>测试订单状态</h2><div class="hint">支付宝回调会自动更新，也可以手动主动查单。</div></div><span id="testStatusTag" class="tag">待支付</span></div><div class="test-result"><div class="row"><span>订单号</span><strong id="testOrderId">-</strong></div><div class="row"><span>金额</span><strong id="testOrderAmount">-</strong></div><div class="row"><span>有效期至</span><span id="testOrderExpiry">-</span></div></div><div class="actions"><button id="refreshTestPayment" type="button" class="btn">主动查询支付宝</button><a id="testPayLink" class="btn primary" target="_blank" rel="noopener noreferrer">打开支付宝支付</a></div></div>
      <div id="testSessionPanel" class="panel hidden"><div class="panel-head"><div><h2>校验充值账号</h2><div class="hint">Session 只经 HTTPS 发送，日志不记录；确认提交后才会加密保存并交给充值任务。</div></div></div><div class="field"><label>粘贴 ChatGPT Session JSON</label><textarea id="testSession" class="session-input" rows="8" autocomplete="off" spellcheck="false" placeholder='包含 user.email 与 accessToken 的完整 JSON'></textarea></div><div id="testEmailBox" class="callout hidden" style="margin-top:16px">检测到邮箱：<b id="testEmail"></b>。请核对无误后再提交。</div><div class="actions"><button id="inspectTestSession" type="button" class="btn">校验并显示邮箱</button><button id="submitTestActivation" type="button" class="btn primary" disabled>确认邮箱并提交充值</button></div></div>
      <div id="testActivationPanel" class="panel hidden"><div class="panel-head"><div><h2>充值结果</h2><div class="hint">充值码全程隐藏，不会返回给用户或平台。</div></div><span id="testActivationTag" class="tag">处理中</span></div><div id="testActivationMessage" class="test-result">任务正在处理，请勿重复提交。</div></div>
    </section>
    <section id="orders" class="view"><div class="panel"><div class="panel-head"><div><h2>订单与财务报表</h2><div class="hint">上游实际成本未知时采用预估成本，并明确标记为“预估”。</div></div></div><div class="toolbar"><div class="field"><label>开始日期</label><input id="from" type="date"></div><div class="field"><label>结束日期</label><input id="to" type="date"></div><button id="query" class="btn primary">查询</button><button id="export" class="btn">导出 CSV</button></div></div><div class="panel"><div id="orderTable"></div></div></section>
  </main>
</div>
<div id="costModal" class="modal hidden"><form id="costForm" class="modal-box"><h3>登记上游实际成本</h3><input type="hidden" name="order_id"><div class="form-grid"><div class="field"><label>原币金额</label><input name="amount" placeholder="例如 20.00"></div><div class="field"><label>币种</label><select name="currency"><option>USD</option><option>CNY</option><option>HKD</option></select></div><div class="field span2"><label>折合人民币成本</label><input name="cny" required placeholder="例如 145.20"><small>财务利润按这个人民币金额计算。</small></div></div><div class="actions"><button type="button" class="btn" onclick="closeCost()">取消</button><button class="btn primary">保存</button></div></form></div>
<div id="toast" class="toast hidden"></div>
<script>
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));let state={config:null,products:[],finance:null,testOrder:null,testTimer:null};
 function money(v){return '¥'+Number(v||0).toFixed(2)}function beijingTime(v){if(!v)return '-';let d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);let p=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(d).reduce((o,x)=>(o[x.type]=x.value,o),{});return p.year+'-'+p.month+'-'+p.day+' '+p.hour+':'+p.minute+':'+p.second}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2500)}
async function api(url,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});let r=await fetch(url,opt);if(r.status===401){$('#login').classList.remove('hidden');throw new Error('请重新登录')}let data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail_zh||data.error||'请求失败');return data}
function go(id){$$('.view').forEach(x=>x.classList.toggle('on',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.view===id));let m={overview:['经营概览','查看交易、结算与利润数据'],config:['接口配置','支付宝与上游密钥在这里填写'],products:['商品与供货价','设置上游成本与平台结算供货价'],test:['联调测试','在后台完成真实支付与充值链路验证'],orders:['订单与财务','对账、成本登记与报表导出']};$('#title').textContent=m[id][0];$('#subtitle').textContent=m[id][1];if(id==='orders')loadFinance()}
$$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/admin/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#login').classList.add('hidden');$('#password').value='';await loadAll()}catch(x){$('#loginError').textContent=x.message}};
$('#logout').onclick=async()=>{await api('/admin/api/logout',{method:'POST'}).catch(()=>{});location.reload()};
async function loadAll(){await Promise.all([loadConfig(),loadProducts(),loadFinance(),loadTestOrders()])}
async function loadConfig(){let d=await api('/admin/api/config');state.config=d;let f=$('#configForm');f.payment_mode.value=d.payment_mode;f.zovo_mode.value=d.zovo_mode;$('#notifyUrl').value=d.alipay_notify_url;let ps=d.payment_mode==='alipay'?'正式支付宝':'测试模式',zs=d.zovo_mode==='live'?'正式上游':'测试模式';$('#payBadge').textContent='支付：'+ps;$('#payBadge').className='badge '+(d.payment_mode==='alipay'&&d.alipay_ready?'good':'warn');$('#zovoBadge').textContent='上游：'+zs;$('#zovoBadge').className='badge '+(d.zovo_mode==='live'&&d.zovo_ready?'good':'warn');setStatus('#alipayStatus',d.alipay_ready,'App ID '+(d.alipay_app_id_masked||'未配置')+' · PID '+(d.alipay_seller_id_masked||'未配置'));setStatus('#zovoStatus',d.zovo_ready,'App ID '+(d.zovo_app_id_masked||'未配置')+' · API 密钥 '+(d.zovo_api_key_masked||'未配置'))}
function setStatus(sel,ok,text){let e=$(sel);e.querySelector('.dot').className='dot '+(ok?'good':'');e.querySelector('span:last-child').textContent=(ok?'已配置 · ':'待配置 · ')+text}
$('#configForm').onsubmit=async e=>{e.preventDefault();let fd=new FormData(e.target),body={};for(let [k,v] of fd)if(String(v).trim())body[k]=String(v).trim();try{await api('/admin/api/config',{method:'PUT',body:JSON.stringify(body)});e.target.querySelectorAll('input:not([readonly]),textarea').forEach(x=>x.value='');toast('配置已加密保存并立即生效');await loadConfig()}catch(x){toast(x.message)}};
async function loadProducts(){let d=await api('/admin/api/products');state.products=d.items;$('#productGrid').innerHTML=d.items.map(p=>'<form class="card product" data-product="'+esc(p.product)+'"><div class="product-title"><div><b>'+esc(p.name_zh)+'</b><small>'+esc(p.product)+'</small></div><label class="switch"><input name="enabled" type="checkbox" '+(p.enabled?'checked':'')+'><span></span></label></div><div class="field"><label>上游预估成本（仅内部）</label><input name="internal_cost_cny" type="number" min="0" step="0.01" value="'+esc(p.internal_cost_cny)+'"></div><div class="field" style="margin-top:12px"><label>给平台供货价</label><input name="cost_price" type="number" min="0" step="0.01" value="'+esc(p.cost_price)+'"><small>可输入 99、99.9 或 99.00，系统会自动规范金额。</small></div><div class="actions"><button class="btn primary">保存商品</button></div></form>').join('');$$('.product').forEach(f=>f.onsubmit=saveProduct);renderTestProducts()}
async function saveProduct(e){e.preventDefault();let f=e.target,b={internal_cost_cny:f.internal_cost_cny.value,cost_price:f.cost_price.value,enabled:f.enabled.checked};try{await api('/admin/api/products/'+encodeURIComponent(f.dataset.product),{method:'PUT',body:JSON.stringify(b)});toast('商品设置已保存');await loadProducts()}catch(x){toast(x.message)}}
function renderTestProducts(){let s=$('#testProduct'),items=state.products.filter(p=>p.enabled),old=s.value;s.innerHTML=items.length?items.map(p=>'<option value="'+esc(p.product)+'">'+esc(p.name_zh)+'（最低 '+money(p.cost_price)+'）</option>').join(''):'<option value="">暂无已启用商品</option>';if(items.some(p=>p.product===old))s.value=old;updateTestPrice();$('#createTestOrder').disabled=!items.length}
function updateTestPrice(){let p=state.products.find(x=>x.product===$('#testProduct').value);if(p)$('#testPrice').value=Number(p.cost_price).toFixed(2)}
 async function loadTestOrders(){try{let d=await api('/admin/api/test/orders'),s=$('#existingTestOrder'),old=s.value;s.innerHTML=d.items.length?'<option value="">请选择已付款测试单</option>'+d.items.map(o=>'<option value="'+esc(o.order_id)+'">'+esc(o.client_order_id)+' · '+esc(o.product)+' · '+money(o.amount)+' · '+beijingTime(o.paid_at)+'</option>').join(''):'<option value="">暂无已付款测试单</option>';if(d.items.some(o=>o.order_id===old))s.value=old;$('#loadExistingTestOrder').disabled=!d.items.length}catch(x){$('#existingTestOrder').innerHTML='<option value="">读取失败，请刷新</option>';$('#loadExistingTestOrder').disabled=true}}
 async function selectExistingTestOrder(){let id=$('#existingTestOrder').value;if(!id)return toast('请先选择已付款测试单');try{let d=await api('/admin/api/test/orders/'+encodeURIComponent(id));state.testOrder=d;$('#testOrderPanel').classList.remove('hidden');$('#testOrderId').textContent=d.order_id;$('#testOrderAmount').textContent=money(d.amount);$('#testOrderExpiry').textContent=beijingTime(d.expires_at);$('#testPayLink').href=d.qr||'#';$('#testSessionPanel').classList.add('hidden');$('#testActivationPanel').classList.add('hidden');renderTestOrderStatus(d.status);startTestPolling();toast('已载入已付款测试单')}catch(x){toast(x.message)}}
$('#loadExistingTestOrder').onclick=selectExistingTestOrder;
$('#testProduct').onchange=updateTestPrice;
 $('#testOrderForm').onsubmit=async e=>{e.preventDefault();let product=$('#testProduct').value,price=Number($('#testPrice').value).toFixed(2);try{let d=await api('/admin/api/test/orders',{method:'POST',body:JSON.stringify({product,sell_price:price})});state.testOrder=d;$('#testOrderPanel').classList.remove('hidden');$('#testOrderId').textContent=d.order_id;$('#testOrderAmount').textContent=money(d.amount);$('#testOrderExpiry').textContent=beijingTime(d.expires_at);$('#testPayLink').href=d.qr;$('#testSessionPanel').classList.add('hidden');$('#testActivationPanel').classList.add('hidden');setTestSteps(1);renderTestOrderStatus(d.status);startTestPolling();toast('测试订单已创建，尚未扣款')}catch(x){toast(x.message)}};
function renderTestOrderStatus(status){let m={pending:'待支付',paid:'已支付',expired:'已过期',refunded:'已退款'},t=$('#testStatusTag');t.textContent=m[status]||status;t.className='tag '+(status==='paid'?'good':status==='expired'||status==='refunded'?'bad':'');if(status==='paid'){$('#testSessionPanel').classList.remove('hidden');setTestSteps(2)}}
function setTestSteps(step){[1,2,3].forEach(n=>{$('#testStep'+n).className='test-step '+(n<step?'done':n===step?'on':'')})}
function startTestPolling(){if(state.testTimer)clearInterval(state.testTimer);pollTestOrder();state.testTimer=setInterval(pollTestOrder,4000)}
async function pollTestOrder(){if(!state.testOrder)return;try{let d=await api('/admin/api/test/orders/'+encodeURIComponent(state.testOrder.order_id));renderTestOrderStatus(d.status);let items=d.activation&&d.activation.items||[],item=items[items.length-1];if(item){$('#testActivationPanel').classList.remove('hidden');let retry=item.status==='failed'&&d.activation.activation_remaining>0;setTestSteps(retry?2:3);let t=$('#testActivationTag');t.textContent=item.status==='success'?'充值成功':retry?'可重新提交':item.status==='failed'?'充值失败':'处理中';t.className='tag '+(item.status==='success'?'good':item.status==='failed'?'bad':'');$('#testActivationMessage').textContent=item.message_zh||'任务正在处理';if(retry)$('#testSessionPanel').classList.remove('hidden');if(item.finished&&state.testTimer){clearInterval(state.testTimer);state.testTimer=null;loadFinance()}}if(d.status==='expired'&&state.testTimer){clearInterval(state.testTimer);state.testTimer=null}}catch(x){}}
$('#refreshTestPayment').onclick=async()=>{if(!state.testOrder)return;try{await api('/admin/api/test/orders/'+encodeURIComponent(state.testOrder.order_id)+'/refresh-payment',{method:'POST'});await pollTestOrder();toast('支付宝订单状态已查询')}catch(x){toast(x.message)}};
$('#testSession').oninput=()=>{$('#testEmailBox').classList.add('hidden');$('#submitTestActivation').disabled=true};
$('#inspectTestSession').onclick=async()=>{if(!state.testOrder)return;let session=$('#testSession').value.trim();if(!session){toast('请先粘贴 Session JSON');return}try{let d=await api('/admin/api/test/orders/'+encodeURIComponent(state.testOrder.order_id)+'/inspect-session',{method:'POST',body:JSON.stringify({session_data:session})});$('#testEmail').textContent=d.email;$('#testEmailBox').classList.remove('hidden');$('#submitTestActivation').disabled=false;toast('Session 格式校验通过，请核对邮箱')}catch(x){toast(x.message)}};
$('#submitTestActivation').onclick=async()=>{if(!state.testOrder||$('#submitTestActivation').disabled)return;let email=$('#testEmail').textContent;if(!confirm('确认给 '+email+' 提交充值？\n\n提交后会真实购买充值码并扣除上游余额，且不会自动退款。'))return;let session=$('#testSession').value;try{let d=await api('/admin/api/test/orders/'+encodeURIComponent(state.testOrder.order_id)+'/activate',{method:'POST',body:JSON.stringify({session_data:session})});$('#testSession').value='';$('#submitTestActivation').disabled=true;$('#testActivationPanel').classList.remove('hidden');$('#testActivationMessage').textContent=d.message_zh;setTestSteps(3);startTestPolling();toast('充值任务已提交')}catch(x){toast(x.message)}};
function dates(){let now=new Date(),to=$('#to').value||now.toISOString().slice(0,10),past=new Date(now-30*86400000),from=$('#from').value||past.toISOString().slice(0,10);$('#from').value=from;$('#to').value=to;return{from:from+'T00:00:00.000Z',to:new Date(to+'T00:00:00.000Z').getTime()+86400000}}
async function loadFinance(){let d=dates(),url='/admin/api/finance?from='+encodeURIComponent(d.from)+'&to='+encodeURIComponent(new Date(d.to).toISOString());let r=await api(url);state.finance=r;$('#mOrders').textContent=r.summary.settlement_orders;$('#mReceipt').textContent=money(r.summary.receipts);$('#mPlatform').textContent=money(r.summary.platform_margin);$('#mProfit').textContent=money(r.summary.gross_profit);renderOrders(r.items);$('#recent').innerHTML=r.items.length?'<div class="hint">最近一笔：'+esc(r.items[0].client_order_id)+' · '+esc(r.items[0].product)+' · '+money(r.items[0].receipt_amount)+'</div>':'<div class="empty">暂无订单，完成联调后会在这里自动出现。</div>'}
 function renderOrders(rows){if(!rows.length){$('#orderTable').innerHTML='<div class="empty">所选时间内暂无订单</div>';return}let h='<div class="table-wrap"><table><thead><tr><th>平台单号 / 我方单号</th><th>商品</th><th>状态</th><th>上游成本</th><th>供货价</th><th>最终售价</th><th>实际收款</th><th>平台差价</th><th>我方毛利</th><th>付款时间（北京时间）</th><th>操作</th></tr></thead><tbody>';h+=rows.map(r=>'<tr><td><strong>'+esc(r.client_order_id)+'</strong><br><span class="hint">'+esc(r.order_id)+'</span></td><td>'+esc(r.product)+'</td><td><span class="tag '+(r.settlement_eligible?'good':r.status==='refunded'?'bad':'')+'">'+esc(r.status_zh)+'</span><br><span class="hint">'+esc(r.delivery_zh)+'</span></td><td>'+money(r.cost_basis_cny)+' <span class="tag">'+(r.cost_is_estimate?'预估':'实际')+'</span></td><td>'+money(r.supply_price)+'</td><td>'+money(r.sell_price)+'</td><td>'+money(r.receipt_amount)+'</td><td class="money plus">'+money(r.platform_margin)+'</td><td class="money '+(Number(r.gross_profit)<0?'minus':'plus')+'">'+money(r.gross_profit)+'</td><td>'+beijingTime(r.paid_at)+'</td><td><button class="btn" onclick="openCost(\''+esc(r.order_id)+'\',\''+esc(r.upstream_actual_cost_amount||'')+'\',\''+esc(r.upstream_actual_cost_currency||'USD')+'\',\''+esc(r.upstream_actual_cost_cny||'')+'\')">登记成本</button></td></tr>').join('');$('#orderTable').innerHTML=h+'</tbody></table></div>'}
$('#query').onclick=loadFinance;$('#export').onclick=()=>{let d=dates();location.href='/admin/api/finance.csv?from='+encodeURIComponent(d.from)+'&to='+encodeURIComponent(new Date(d.to).toISOString())};
function openCost(id,amount,currency,cny){let f=$('#costForm');f.order_id.value=id;f.amount.value=amount;f.currency.value=currency;f.cny.value=cny;$('#costModal').classList.remove('hidden')}function closeCost(){$('#costModal').classList.add('hidden')}
$('#costForm').onsubmit=async e=>{e.preventDefault();let f=e.target;try{await api('/admin/api/orders/'+encodeURIComponent(f.order_id.value)+'/cost',{method:'PUT',body:JSON.stringify({amount:f.amount.value||null,currency:f.currency.value||null,cny:f.cny.value})});closeCost();toast('实际成本已登记');await loadFinance()}catch(x){toast(x.message)}};
(async()=>{try{await api('/admin/api/session');$('#login').classList.add('hidden');await loadAll()}catch{}})();
</script></body></html>`;
